# Generated by Django 5.1 on 2024-09-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0005_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='my_first_app.author'),
        ),
    ]
