# Generated by Django 5.1 on 2024-09-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0007_alter_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='autores',
        ),
    ]
